#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run with sudo: sudo bash $0" >&2
  exit 1
fi

BASE="/etc/kai9000/cloudflare"
NGINX_CERT_DIR="/etc/nginx/certs"
install -d -m 0755 "$BASE" "$NGINX_CERT_DIR"

curl -fsSL https://www.cloudflare.com/ips-v4 -o "$BASE/ips-v4.txt"
curl -fsSL https://www.cloudflare.com/ips-v6 -o "$BASE/ips-v6.txt"
curl -fsSL https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem -o "$NGINX_CERT_DIR/cloudflare.crt"
chmod 0644 "$BASE/ips-v4.txt" "$BASE/ips-v6.txt" "$NGINX_CERT_DIR/cloudflare.crt"

cat > "$BASE/README.txt" <<NOTE
Generated by KAI update-cloudflare-public-trust.sh
- ips-v4.txt and ips-v6.txt are public Cloudflare egress ranges for proxied origins.
- /etc/nginx/certs/cloudflare.crt is the public CA certificate used to validate Cloudflare Authenticated Origin Pull client certs.
- No private key material is fetched or stored by this script.
NOTE

echo "Cloudflare public trust material refreshed under $BASE and $NGINX_CERT_DIR/cloudflare.crt"
