(()=>{
  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  const manifest=JSON.parse(q('#demo-manifest').textContent), assets=window.LUHM_ASSET_REGISTRY;
  const privateByName=new Map(assets.private_art.entries.map(x=>[x.name,x]));
  function tab(name){qa('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));qa('.view').forEach(v=>v.classList.toggle('active',v.id===name));}
  qa('.tab').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));qa('[data-jump]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.jump)));
  function rows(host,items,render){host.replaceChildren(...items.map((x,i)=>{const d=document.createElement('div');d.className='asset-row';render(d,x,i);return d;}));}
  rows(q('#privateArtList'),assets.private_art.entries,(d,x)=>{const a=document.createElement('span'),b=document.createElement('code');a.textContent=x.name;b.textContent=x.sha256.slice(0,12)+'…';d.append(a,b);});
  rows(q('#modelSources'),assets.three_d.sources,(d,x,i)=>{const a=document.createElement('span'),b=document.createElement('span');a.textContent=String(i+1).padStart(2,'0')+' · '+x.name;b.textContent=x.license+' · '+x.role;b.className='small';d.append(a,b);});
  rows(q('#questVisuals'),assets.questforge.generation_ids,(d,x,i)=>{const a=document.createElement('span'),b=document.createElement('code');a.textContent='Visual '+(i+1);b.textContent=x;d.append(a,b);});
  async function digest(file){if(!globalThis.crypto?.subtle)return null;const buf=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',buf);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  q('#artFiles').addEventListener('change',async e=>{const host=q('#artMountResults');host.replaceChildren();for(const file of [...e.target.files]){const box=document.createElement('div');box.className='preview';const img=document.createElement('img');img.alt=file.name;img.src=URL.createObjectURL(file);const label=document.createElement('small');const expected=privateByName.get(file.name);const got=await digest(file);let state='UNINDEXED LOCAL';if(expected&&got)state=got===expected.sha256?'HASH MATCH ✓':'HASH MISMATCH';else if(expected)state='NAME MATCH · HASH API UNAVAILABLE';label.textContent=file.name+' · '+state;box.append(img,label);host.append(box);}});
  q('#modelFiles').addEventListener('change',e=>{const files=[...e.target.files];rows(q('#modelMountResults'),files,(d,f)=>{const a=document.createElement('span'),b=document.createElement('span');a.textContent=f.name;b.textContent=Math.round(f.size/1024)+' KiB · LOCAL INSPECTION ONLY';b.className='small';d.append(a,b);});});
  q('#runAudit').addEventListener('click',()=>{const checks=[
    ['Crown',manifest.source_of_truth.crown_id==='CROWN_SOURCE_OF_TRUTH_20260919'],['Authority',manifest.source_of_truth.human_final_authority==='Professor'&&manifest.source_of_truth.boss_ai==='Lum'],['Roleplay wall',manifest.source_of_truth.roleplay_hard_separation&&manifest.source_of_truth.questforge_engineering_authority===false],['Public assets',assets.public.length===manifest.assets.public_forge_bundle_count],['Private art index',assets.private_art.entries.length===manifest.assets.private_original_art_index_count],['Private upload blocked',manifest.demo_contract.private_assets_never_auto_uploaded===true],['Quest visuals',assets.questforge.generation_ids.length===manifest.questforge.visual_reference_count],['3D source registry',assets.three_d.sources.length===manifest.assets.three_d_source_registry_count],['3D runtime truth',manifest.assets.repo_model_binary_count===0&&manifest.assets.three_d_runtime_status==='REGISTRY_ONLY_NO_APPROVED_BINARY_IN_GIT'],['Android not inflated',manifest.evidence.android_green==='PENDING_DEVICE_VALIDATION']];
    const ok=checks.every(x=>x[1]);q('#console').textContent=checks.map(x=>(x[1]?'PASS ':'FAIL ')+x[0]).join('\n')+'\n\n'+(ok?'LOCAL SELF AUDIT: PASS':'LOCAL SELF AUDIT: FAIL');
  });
  q('#showReceipt').addEventListener('click',()=>{q('#console').textContent='DEMO '+manifest.id+'\nASSET REGISTRY '+assets.id+'\nPUBLIC SAFE '+assets.public.length+'\nPRIVATE ORIGINAL INDEX '+assets.private_art.entries.length+'\nQUESTFORGE VISUAL REFS '+assets.questforge.generation_ids.length+'\n3D SOURCES '+assets.three_d.sources.length+'\n3D BINARIES '+assets.three_d.repo_binary_count+'\nPRIVATE FILES NEVER AUTO-UPLOAD';});
})();
